# ===========================================================
# DEFINES (SHARED)
# ===========================================================

# Programs
$terminal = kitty
$fileManager = kitty yazi
$menu = rofi -show
$browser = firefox

# Directories
$home = /home/miguel
$screenshots = /home/miguel/Pictures/Screenshots
$scripts = /home/miguel/.config/hypr/scripts

# Colors
$bcolor1 = 7018bcff
$bcolor2 = bc18b7ff
$bcolori = 38383850
$shadow  = 1a1a1aee
