# ===========================================================
# HYPRLAND ROOT ORCHESTRATOR
# ===========================================================

source = ~/.config/hypr/defines.conf
source = ~/.config/hypr/machine.conf
source = ~/.config/hypr/environments.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/visual.conf
source = ~/.config/hypr/shared_rules.conf
source = ~/.config/hypr/shared_binds.conf
