# ===========================================================
# ENVIRONMENTS (HARDWARE: DESKTOP)
# ===========================================================

# Cursor Settings
env = XCURSOR_SIZE, 16
env = HYPRCURSOR_SIZE, 16
env = XCURSOR_THEME, Bibata-Modern-Ice
env = HYPRCURSOR_THEME, Bibata-Modern-Ice

# Wayland Settings
env = MOZ_ENABLE_WAYLAND, 1
env = QT_QPA_PLATFORM, wayland;xcb
env = QT_QPA_PLATFORMTHEME, qt6ct

# XDG Settings
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland

# Keyboard
env = XMODIFIERS, @im=fcitx

# Programs
env = SALT_LICENSE_SERVER, $home/.questa_license.dat #QUARTUS
